# https://github.com/ndmitchell/hlint#customizing-the-hints

- arguments: [ --cmdthreads, --cross ]

- extensions:
  - default: false
  - name:
      - DeriveGeneric

- group: { name: dollar, enabled: true }

- ignore: { name: Eta reduce }
