name: semabadge
version: 0.0.0

category: Web
description: Semabadge generates deploy badges for Semaphore.
extra-source-files:
  - package.yaml
  - README.markdown
  - stack.yaml
github: tfausak/semabadge
license-file: LICENSE.markdown
license: MIT
maintainer: Taylor Fausak
synopsis: Generates deploy badges for Semaphore.

dependencies:
  aeson: '>= 0.11.2 && < 0.12 || >= 1.0.2 && < 1.3'
  barrier: '>= 0.1.1 && < 0.2'
  base: '>= 4.9.0 && < 4.12'
  bytestring: '>= 0.10.8 && < 0.11'
  http-client-tls: '>= 0.2.4 && < 0.4'
  http-client: '>= 0.4.31 && < 0.6'
  http-types: '>= 0.9.1 && < 0.13'
  text: '>= 1.2.2 && < 1.3'
  wai: '>= 3.2.1 && < 3.3'
  warp: '>= 3.2.8 && < 3.3'
ghc-options:
  - -optP -Wno-nonportable-include-path # https://github.com/haskell/cabal/issues/4739
  - -Weverything
  - -Wno-implicit-prelude
  - -Wno-safe
  - -Wno-unsafe

library:
  source-dirs: library

executable:
  dependencies:
    semabadge: -any
  ghc-options:
    - -rtsopts
    - -threaded
  main: Main.hs
  source-dirs: executables

tests:
  test:
    dependencies:
      hspec: '>= 2.2.3 && < 2.6'
      semabadge: -any
    ghc-options:
      - -rtsopts
      - -threaded
      - -Wno-missing-import-lists
    main: Main.hs
    source-dirs: tests
