name: semabadge
version: 0.0.0

category: Web
description: Semabadge generates deploy badges for Semaphore.
extra-source-files:
  - package.yaml
  - README.markdown
  - stack.yaml
github: tfausak/semabadge
license-file: LICENSE.markdown
license: MIT
maintainer: Taylor Fausak
synopsis: Generates deploy badges for Semaphore.

dependencies:
  aeson: '>= 1.2.4 && < 1.4'
  barrier: '>= 0.1.1 && < 0.2'
  base: '>= 4.10.1 && < 4.12'
  bytestring: '>= 0.10.8 && < 0.11'
  envy: '>= 1.5.0 && < 1.6'
  http-client-tls: '>= 0.3.5 && < 0.4'
  http-client: '>= 0.5.10 && < 0.6'
  http-types: '>= 0.12.1 && < 0.13'
  microlens: '>= 0.4.8 && < 0.5'
  scotty: '>= 0.11.0 && < 0.12'
  text: '>= 1.2.3 && < 1.3'
  wai-extra: '>= 3.0.22 && < 3.1'
  warp: '>= 3.2.18 && < 3.3'
ghc-options:
  - -optP -Wno-nonportable-include-path # https://github.com/haskell/cabal/issues/4739
  - -Weverything
  - -Wno-implicit-prelude
  - -Wno-safe
  - -Wno-unsafe

executable:
  ghc-options:
    - -rtsopts
    - -threaded
  main: semabadge.hs
